name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
      
      - name: Prepare files for deployment
        run: |
          rm -rf deploy && mkdir deploy
          cp frontend/index.html deploy
          cp -r frontend/dist deploy/

      - name: Deploy to droplet
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "deploy/*"
          target: "/var/www/hangman"
          overwrite: true
          strip_components: 1

  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend
        working-directory: ./backend
        run: |
          mkdir -p build
          cd ./build
          cmake ..
          make
          ls -A

      - name: Deploy to droplet
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "backend/build/hangmanbackend"
          target: "/var/www/hangman"
          overwrite: true